name: Unit Test

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main, develop]

jobs:
  unit_test:
    name: unit_test
    runs-on: ubuntu-22.04
    steps:
      - name: maximize build space
        uses: easimon/maximize-build-space@fc881a613ad2a34aca9c9624518214ebc21dfc0c # ratchet:easimon/maximize-build-space@v10
        with:
          root-reserve-mb: 38912
          swap-size-mb: 4096
          remove-dotnet: "true"
          remove-android: "true"
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - run: |
          git apply tests/0001-diff-go-ethereum.patch
          make test
