name: Unit Test

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main, develop]

jobs:
  unit_test:
    name: unit_test
    runs-on: ubuntu-22.04
    steps:
      - name: Increase swapfile
        run: |
          sudo swapoff -a
          sudo fallocate -l 15G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          sudo swapon --show
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - run: |
          git apply tests/0001-diff-go-ethereum.patch
          make test
